version: '3.9'

services:
  redis:
    image: redis:alpine
    command: 
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6378:6378"
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports: 
      - "5432:5432"
  bot:
    container_name: diet-advisor-bot
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - db

volumes:
  pgdata: